# Install script for directory: /root/softm/percona-server-5.7.22-22

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/mysqldata/mysql3306")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "RelWithDebInfo")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "0")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Info")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/docs" TYPE FILE OPTIONAL FILES "/root/softm/percona-server-5.7.22-22/Docs/mysql.info")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Info")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Readme")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE OPTIONAL FILES
    "/root/softm/percona-server-5.7.22-22/COPYING"
    "/root/softm/percona-server-5.7.22-22/LICENSE.mysql"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Readme")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Readme")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE FILES "/root/softm/percona-server-5.7.22-22/README.MySQL")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Readme")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/docs" TYPE FILE FILES
    "/root/softm/percona-server-5.7.22-22/Docs/INFO_SRC"
    "/root/softm/percona-server-5.7.22-22/Docs/INFO_BIN"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Documentation")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/docs" TYPE DIRECTORY FILES "/root/softm/percona-server-5.7.22-22/Docs/" REGEX "/Makefile\\.[^/]*$" EXCLUDE REGEX "/glibc[^/]*$" EXCLUDE REGEX "/linuxthreads\\.txt$" EXCLUDE REGEX "/myisam\\.txt$" EXCLUDE REGEX "/mysql\\.info$" EXCLUDE REGEX "/sp\\-imp\\-spec\\.txt$" EXCLUDE)
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Documentation")

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/root/softm/percona-server-5.7.22-22/extra/yassl/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/extra/yassl/taocrypt/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/libevent/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/extra/protobuf/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/include/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/dbug/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/strings/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/vio/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/regex/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/mysys/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/mysys_ssl/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/libmysql/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/libbinlogevents/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/libbinlogstandalone/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/perfschema/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/innobase/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/example/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/partition/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/tokudb/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/ndb/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/myisam/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/blackhole/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/heap/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/federated/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/rocksdb/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/csv/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/archive/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/storage/myisammrg/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/test_services/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/rewriter/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/audit_null/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/udf_services/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/fulltext/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/innodb_memcached/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/keyring_vault/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/version_token/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/audit_log/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/scalability_metrics/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/daemon_example/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/connection_control/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/test_service_sql_api/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/query_response_time/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/rewrite_example/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/semisync/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/password_validation/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/auth/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/percona-udf/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/tokudb-backup-plugin/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/keyring/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/replication_observers_example/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/plugin/percona-pam-for-mysql/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/rapid/plugin/keyring_udf/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/rapid/plugin/x/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/rapid/plugin/group_replication/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/unittest/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/unittest/examples/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/unittest/mytap/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/unittest/mytap/t/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/rapid/unittest/gunit/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/extra/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/client/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/sql/share/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/libservices/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/man/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/testclients/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/sql/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/libmysqld/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/libmysqld/examples/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/scripts/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/mysql-test/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/mysql-test/lib/My/SafeProcess/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/support-files/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/packaging/rpm-common/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/packaging/rpm-oel/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/packaging/rpm-fedora/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/packaging/rpm-sles/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/packaging/rpm-docker/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/packaging/deb-in/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/packaging/WiX/cmake_install.cmake")
  INCLUDE("/root/softm/percona-server-5.7.22-22/packaging/solaris/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "/root/softm/percona-server-5.7.22-22/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "/root/softm/percona-server-5.7.22-22/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
