var searchData=
[
  ['rand_5flog_5fevent',['Rand_log_event',['../classRand__log__event.html',1,'']]],
  ['range_5fopt_5fparam',['RANGE_OPT_PARAM',['../classRANGE__OPT__PARAM.html',1,'']]],
  ['range_5foptimizer_5ferror_5fhandler',['Range_optimizer_error_handler',['../classRange__optimizer__error__handler.html',1,'']]],
  ['rapid_5fjson_5fhandler',['Rapid_json_handler',['../classRapid__json__handler.html',1,'']]],
  ['read_5finfo',['READ_INFO',['../classREAD__INFO.html',1,'']]],
  ['read_5frecord',['READ_RECORD',['../structREAD__RECORD.html',1,'']]],
  ['rebind',['rebind',['../structMemroot__allocator_1_1rebind.html',1,'Memroot_allocator&lt; T &gt;::rebind&lt; U &gt;'],['../structMalloc__allocator_1_1rebind.html',1,'Malloc_allocator&lt; T &gt;::rebind&lt; U &gt;']]],
  ['regex',['Regex',['../classRegex.html',1,'']]],
  ['relay_5flog_5finfo',['Relay_log_info',['../classRelay__log__info.html',1,'']]],
  ['release_5fall_5flocking_5fservice_5flocks',['Release_all_locking_service_locks',['../classRelease__all__locking__service__locks.html',1,'']]],
  ['release_5flocking_5fservice_5flocks',['Release_locking_service_locks',['../classRelease__locking__service__locks.html',1,'']]],
  ['repair_5fmrg_5ftable_5ferror_5fhandler',['Repair_mrg_table_error_handler',['../classRepair__mrg__table__error__handler.html',1,'']]],
  ['reprepare_5fobserver',['Reprepare_observer',['../classReprepare__observer.html',1,'']]],
  ['reset_5fthd_5fstatus',['Reset_thd_status',['../classReset__thd__status.html',1,'']]],
  ['revtinfo',['revtinfo',['../structrevtinfo.html',1,'']]],
  ['ring_5fconst_5ftype_3c_20gis_5fpolygon_20_3e',['ring_const_type&lt; Gis_polygon &gt;',['../structboost_1_1geometry_1_1traits_1_1ring__const__type_3_01Gis__polygon_01_4.html',1,'boost::geometry::traits']]],
  ['ring_5fconst_5ftype_3c_20gis_5fpolygon_5fspherical_20_3e',['ring_const_type&lt; Gis_polygon_spherical &gt;',['../structboost_1_1geometry_1_1traits_1_1ring__const__type_3_01Gis__polygon__spherical_01_4.html',1,'boost::geometry::traits']]],
  ['ring_5fmutable_5ftype_3c_20gis_5fpolygon_20_3e',['ring_mutable_type&lt; Gis_polygon &gt;',['../structboost_1_1geometry_1_1traits_1_1ring__mutable__type_3_01Gis__polygon_01_4.html',1,'boost::geometry::traits']]],
  ['ring_5fmutable_5ftype_3c_20gis_5fpolygon_5fspherical_20_3e',['ring_mutable_type&lt; Gis_polygon_spherical &gt;',['../structboost_1_1geometry_1_1traits_1_1ring__mutable__type_3_01Gis__polygon__spherical_01_4.html',1,'boost::geometry::traits']]],
  ['ror_5fintersect_5finfo',['ROR_INTERSECT_INFO',['../structROR__INTERSECT__INFO.html',1,'']]],
  ['rotate_5finnodb_5fmaster_5fkey',['Rotate_innodb_master_key',['../classRotate__innodb__master__key.html',1,'']]],
  ['rotate_5flog_5fevent',['Rotate_log_event',['../classRotate__log__event.html',1,'']]],
  ['rows_5flog_5fevent',['Rows_log_event',['../classRows__log__event.html',1,'']]],
  ['rows_5fquery_5flog_5fevent',['Rows_query_log_event',['../classRows__query__log__event.html',1,'']]],
  ['rpl_5fevent_5fcoordinates',['rpl_event_coordinates',['../structrpl__event__coordinates.html',1,'']]],
  ['rpl_5ffilter',['Rpl_filter',['../classRpl__filter.html',1,'']]],
  ['rpl_5finfo',['Rpl_info',['../classRpl__info.html',1,'']]],
  ['rpl_5finfo_5fdummy',['Rpl_info_dummy',['../classRpl__info__dummy.html',1,'']]],
  ['rpl_5finfo_5ffile',['Rpl_info_file',['../classRpl__info__file.html',1,'']]],
  ['rpl_5finfo_5fhandler',['Rpl_info_handler',['../classRpl__info__handler.html',1,'']]],
  ['rpl_5finfo_5ftable',['Rpl_info_table',['../classRpl__info__table.html',1,'']]],
  ['rpl_5finfo_5ftable_5faccess',['Rpl_info_table_access',['../classRpl__info__table__access.html',1,'']]],
  ['rpl_5finfo_5fvalues',['Rpl_info_values',['../classRpl__info__values.html',1,'']]],
  ['rpl_5ftable_5flist',['RPL_TABLE_LIST',['../structRPL__TABLE__LIST.html',1,'']]],
  ['rpl_5fthd_5fcontext',['Rpl_thd_context',['../classRpl__thd__context.html',1,'']]],
  ['rpl_5ftransaction_5fctx',['Rpl_transaction_ctx',['../classRpl__transaction__ctx.html',1,'']]],
  ['rpl_5ftransaction_5fwrite_5fset_5fctx',['Rpl_transaction_write_set_ctx',['../classRpl__transaction__write__set__ctx.html',1,'']]],
  ['rtree_5fentry_5fcompare',['Rtree_entry_compare',['../classRtree__entry__compare.html',1,'']]],
  ['rtree_5fvalue_5fmaker',['Rtree_value_maker',['../structRtree__value__maker.html',1,'']]],
  ['rtree_5fvalue_5fmaker_5fbggeom',['Rtree_value_maker_bggeom',['../structRtree__value__maker__bggeom.html',1,'']]],
  ['run_5ffree_5ffunction',['Run_free_function',['../classRun__free__function.html',1,'']]],
  ['run_5fhton_5ffill_5fschema_5ftable_5fargs',['run_hton_fill_schema_table_args',['../structrun__hton__fill__schema__table__args.html',1,'']]]
];
